/* eslint-disable quote-props */
// eslint-disable-next-line no-unused-vars
/* global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "Extended logging": { en: "Extended logging", de: "Erweiterte Protokollierung", ru: "Расширенное ведение журнала", pt: "Registro estendido", nl: "Uitgebreide logboekregistratie", fr: "Journalisation étendue", it: "Registrazione estesa", es: "Registro extendido", pl: "Rozszerzone logowanie", uk: "Розширений журнал", "zh-cn": "扩展日志记录" },
    "Name": { en: "Name", de: "Name", ru: "Имя", pt: "Nome", nl: "Naam", fr: "Nom", it: "Nome", es: "Nombre", pl: "Nazwa", uk: "Ім'я", "zh-cn": "姓名" },
    "IP Adress": { en: "IP Adress", de: "IP Adresse", ru: "IP адрес", pt: "Endereço de IP", nl: "IP adres", fr: "Adresse IP", it: "Indirizzo IP", es: "Dirección IP", pl: "Adres IP", uk: "Веб-камера", "zh-cn": "IP地址" },
    "Port": { en: "Port", de: "Port", ru: "Порт", pt: "Porta", nl: "Port", fr: "Port", it: "Porta", es: "Puerto", pl: "Port", uk: "Портфоліо", "zh-cn": "港口" },
    "Smart name": { en: "Smart name", de: "Smart Name", ru: "Умное имя", pt: "Nome inteligente", nl: "Slimme naam", fr: "Nom intelligent", it: "Nome intelligente", es: "Nombre inteligente", pl: "Inteligentna nazwa", uk: "Розумне ім'я", "zh-cn": "聪明的名字" },
    "Type": { en: "Type", de: "Typ", ru: "Тип", pt: "Modelo", nl: "Type", fr: "Taper", it: "Tipo", es: "Escribe", pl: "Rodzaj", uk: "Тип", "zh-cn": "类型" },
    "blebox adapter settings": { en: "Adapter settings for blebox", de: "Adaptereinstellungen für blebox", ru: "Настройки адаптера для blebox", pt: "Configurações do adaptador para blebox", nl: "Adapterinstellingen voor blebox", fr: "Paramètres d'adaptateur pour blebox", it: "Impostazioni dell'adattatore per blebox", es: "Ajustes del adaptador para blebox", pl: "Ustawienia adaptera dla blebox", "zh-cn": "blebox的适配器设置" }
};
